server:
  port: 8080

spring:
  application:
    name: chagok
  banner:
    location: banner.txt

  profiles:
    include: secret

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    open-in-view: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DB_DRIVER}
    hikari:
      maximum-pool-size: 10

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  jwt:
    secret-key: ${JWT_SECRET}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET}
            scope:
              - name
              - email
              - gender
              - age
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    #    com.zaxxer.hikari: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# cors 설정
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/callback/naver
